name: Process Weekly Notifications
on:
  schedule:
    - cron: '0 15 * * 0'  # Runs every Sunday at 15:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  execute-process-weekly:
    runs-on: ubuntu-latest
    environment: production # Change if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: site/gatsby-site/package-lock.json

      - name: Install dependencies
        working-directory: site/gatsby-site
        run: npm ci

      - name: Process Weekly Notifications
        working-directory: site/gatsby-site
        env:
          API_MONGODB_CONNECTION_STRING: ${{ secrets.API_MONGODB_CONNECTION_STRING }}
          ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN: ${{ secrets.ROLLBAR_POST_SERVER_ITEM_ACCESS_TOKEN }}
          MAILERSEND_API_KEY: ${{ secrets.MAILERSEND_API_KEY }}
          NOTIFICATIONS_SENDER_NAME: ${{ vars.NOTIFICATIONS_SENDER_NAME }}
          NOTIFICATIONS_SENDER: ${{ vars.NOTIFICATIONS_SENDER }}
          SITE_URL: ${{ vars.SITE_URL }}
          NEXTAUTH_URL: ${{ vars.SITE_URL }} # NextAuth requires this variable
          NEXTAUTH_SECRET: dummy # No actual secret needed unless sending magic links
        run: npm run process-weekly-notifications:ci
